export * from "./types.js";
export { parseDoc, serializeDoc, hasNonEmptyType } from "./frontmatter.js";
export { Bundle, BundleError, replaceSection } from "./bundle.js";
export { regenerateIndex, regenerateIndexChain, pruneEmptyDirs } from "./indexer.js";
export { appendLog, readLog } from "./logger.js";
export { searchBundle, listTypes, matchesFilters, inDirectory, type SearchOptions } from "./search.js";
export { validateBundle } from "./validate.js";
export { normalizeSources, mergeSources, MAX_SOURCES, type ConceptSource } from "./sources.js";
export { normalizeHistory, appendHistory, MAX_HISTORY, type Supersession } from "./history.js";
export { addTombstones, forgottenRefs, forgottenInText, hashRef } from "./tombstone.js";
export { lintBundle } from "./lint.js";
export type { LintReport, LintFinding, BrokenLink } from "./lint.js";
export { buildGraph, scanGraph } from "./graph.js";
export type { GraphData, GraphNode, GraphEdge } from "./graph.js";
export { KnowledgeBase, type KnowledgeBaseOptions, type RollbackReport } from "./knowledge-base.js";
export { Journal } from "./journal.js";
